version: 1.3.{build}
skip_tags: true
image: Visual Studio 2022
configuration: Release
dotnet_csproj:
  patch: true
  file: '.msbuild\custom.targets'
  version: '{version}'
  file_version: '{version}'
  package_version: '{version}'
  informational_version: $(APPVEYOR_REPO_BRANCH):$(APPVEYOR_REPO_COMMIT)
before_build:
  - cmd: |
      setlocal enabledelayedexpansion
      setlocal EnableExtensions

      REM Set version attributes..
      Tools\UnixUtils\sed.exe -i -e "s|0\.0\.0\.0|%APPVEYOR_BUILD_VERSION%|g" .msbuild\custom.targets
      Tools\UnixUtils\sed.exe -i -e "s|GIT_COMMIT|%APPVEYOR_REPO_COMMIT%|g" .msbuild\custom.targets
      Tools\UnixUtils\sed.exe -i -e "s|VERSION_STRING|%APPVEYOR_REPO_BRANCH%:%APPVEYOR_REPO_COMMIT%|g" .msbuild\custom.targets

      REM Restoring NuGet packages..
      appveyor-retry nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  verbosity: normal
before_test:
  - cmd: |
      set PATH=C:\Tools\NUnit3\bin;%APPVEYOR_BUILD_FOLDER%\packages\Machine.Specifications.Runner.Console.1.0.0\tools;%PATH%
      REM Remove Machine.Specifications VS Adapter dlls
      del %APPVEYOR_BUILD_FOLDER%\HermaFx.SimpleConfig.Tests\bin\Release\Machine.*
      del %APPVEYOR_BUILD_FOLDER%\HermaFx.SimpleConfig.Tests\bin\Release\Mono.*
      REM Remove Castle.Core.dll too, as to ensure no dependency against it exists (due to ilmergin)
      del %APPVEYOR_BUILD_FOLDER%\HermaFx.SimpleConfig.Tests\bin\Release\Castle.*
after_test:
  - ps: |
      #$wc = New-Object 'System.Net.WebClient'
      #$wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))
deploy:
  - provider: NuGet
    api_key:
      secure: 9KkW6zvhDTGsJuXI70tXZznNwskIqnYj3l0iF84UcOdYV4oQRzPytdw2nDQZGk7r
    on:
      branch: master
notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true

