<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Title>HermaFx.Rebus.Tests</Title>
    <Description>HermaFx rebus unit tests</Description>
    <TargetFramework>net472</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>HermaFx.Rebus.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\HermaFx.Rebus\HermaFx.Rebus.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.2.0" />
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.4.2" />
  </ItemGroup>
  <Import Project="$(ProjectDir)..\.msbuild\custom.targets"/>
</Project>